// Generated by `npm run docs:props` (scripts/build-component-docs.mjs) —
// do not hand-edit props.generated.json, re-run the script instead.
import raw from "./props.generated.json";

export interface PropDoc {
  name: string;
  type: string;
  required: boolean;
  defaultValue: string | null;
  description: string;
}

export interface ComponentDoc {
  description: string;
  props: PropDoc[];
}

export const COMPONENT_DOCS: Record<string, ComponentDoc> = raw;
